substitutions:
  _DOCKERFILE: services/chat-api/Dockerfile
  _IMAGE_NAME: omniagent-chat
  _IMAGE_TAG: dev
  _IMAGE_REPOSITORY: us-central1-docker.pkg.dev/gen-lang-client-0593591102/janusai-poc
  _OMNIAGENT_GOOGLE_CLIENT_ID: ""

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=${_DOCKERFILE}
      - --build-arg=OMNIAGENT_GOOGLE_CLIENT_ID=${_OMNIAGENT_GOOGLE_CLIENT_ID}
      - --tag=${_IMAGE_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args: [push, "${_IMAGE_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}"]

images:
  - ${_IMAGE_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
